### ISSUE TITLE
Sample file "CyTOF_ClusterCellTypes_Panel3.xlsx"?

### ISSUE THREAD

**Issue by molecules** [casanova-lab/iMUBAC#13]
Is the file "CyTOF_ClusterCellTypes_Panel3.xlsx" available as a sample input file (i.e. one mentioned in your sample code)?

**Comment by casanova-lab** [comment]
Hi,

Attached is the sample excel table.
Thanks for your interest.

Best wishes,
Masato
________________________________
From: Christopher Bottoms ***@***.***>
Sent: Monday, May 23, 2022 1:23 PM
To: casanova-lab/iMUBAC ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [casanova-lab/iMUBAC] Sample file "CyTOF_ClusterCellTypes_Panel3.xlsx"? (Issue #13)

Caution: External email

Is the file "CyTOF_ClusterCellTypes_Panel3.xlsx" available as a sample input file (i.e. one mentioned in your sample code)?

**Comment by casanova-lab** [comment]
[CyTOF_ClusterCellTypes_Panel3.xlsx](https://github.com/casanova-lab/iMUBAC/files/8757230/CyTOF_ClusterCellTypes_Panel3.xlsx)

**Comment by molecules** [comment]
Thank you!
