### ISSUE TITLE
Run without transformation

### ISSUE THREAD

**Issue by Stacheltier** [casanova-lab/iMUBAC#15]
Hi,

thank You for this package. When using the example script, I wondered if it is possible to omit the "arcsin" transformation when creating the SCE object?

Best,
Sebastian

**Comment by casanova-lab** [comment]
Hi Sebastian,

Thank you for your interest. Now "type" can be set NULL to omit cytometry-specific data transformation.

Regards,
Masato

**Comment by Stacheltier** [comment]
Dear Masato,

thank You very much!
Sebastian
