### ISSUE TITLE
Quick-TRANSfer stage steps exceeded maximum

### ISSUE THREAD

**Issue by EzequielD-86** [casanova-lab/iMUBAC#17]
Hello! Thank you for this wonderful package. I was reaching out because I am using iMUBAC with a large dataset and seems like there is an issue with Harmony. Please see below: 

Harmony converged after 5 iterations
Warning messages:
1: Quick-TRANSfer stage steps exceeded maximum (= 9998700) 
2: Quick-TRANSfer stage steps exceeded maximum (= 9998700) 
3: Quick-TRANSfer stage steps exceeded maximum (= 9998700) 
4: Quick-TRANSfer stage steps exceeded maximum (= 9998700) 
5: Quick-TRANSfer stage steps exceeded maximum (= 9998700) 

Looks like this is a well described issue, do you think there is a way of addressing this within iMUBAC? THANKS !

**Comment by casanova-lab** [comment]
Hi, 

Thanks for your interest in our package. I actually think that your Harmony steps converged successfully, despite the warning message. You can visually examine the cellular distributions pre-/post-Harmonization by UMAP etc. Good luck with your research.

Best,
Masato
